openapi: 3.0.0
info:
  title: Forgot Password API
  version: 1.0.0
paths:
  /forgot-password:
    post:
      summary: Request a password reset link
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
              required:
                - email
      responses:
        '200':
          description: Password reset link sent (or message indicating if email is registered)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: If a user with that email exists, a password reset link has been sent.
        '400':
          description: Invalid email format
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Invalid email format
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: An unexpected error occurred
