openapi: 3.0.0
info:
  title: Reset Password API
  version: 1.0.0
paths:
  /reset-password:
    post:
      summary: Reset user password using a valid token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: some_jwt_reset_token
                new_password:
                  type: string
                  format: password
                  minLength: 8
                  example: NewStrongP@ssw0rd!
              required:
                - token
                - new_password
      responses:
        '200':
          description: Password successfully reset
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password reset successfully
        '400':
          description: Invalid input or password policy violation
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Invalid token, Token expired, or Password does not meet requirements
        '401':
          description: Unauthorized (e.g., invalid or expired token)
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Invalid or expired password reset token
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: An unexpected error occurred
